spring:
  http:
    log-request-details: true
    encoding:
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG